# Generated by Django 3.1.3 on 2020-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201120_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image',
        ),
        migrations.AddField(
            model_name='notebook',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 4'),
        ),
    ]
