# Generated by Django 3.1.3 on 2020-11-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201121_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='image1',
            field=models.ImageField(upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image1',
            field=models.ImageField(upload_to='', verbose_name='Фото 1'),
        ),
    ]
