# Generated by Django 3.1.3 on 2020-11-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201121_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 5'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image6',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 6'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image7',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image8',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 5'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image6',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 6'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image7',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image8',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 8'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 1'),
        ),
    ]
