# Generated by Django 3.1.3 on 2020-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201121_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image8',
        ),
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
