# Generated by Django 3.1.3 on 2020-11-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201121_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='final_price',
            new_name='total_price',
        ),
    ]
