# Generated by Django 3.1.3 on 2020-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201121_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество продуктов'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Цена'),
        ),
    ]
