# Generated by Django 3.1.3 on 2020-11-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20201123_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order1',
        ),
    ]
