# Generated by Django 3.1.3 on 2020-11-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20201123_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
