# Generated by Django 3.1.3 on 2020-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20201123_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=63, verbose_name='Электронная почта'),
        ),
    ]
