# Generated by Django 3.1.3 on 2020-11-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.CharField(default='бесплатно', max_length=9, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_method',
            field=models.ForeignKey(choices=[('self', 'Курьером в удобный для вас день'), ('delivery', 'Самовывоз'), ('post', 'Почтой')], default='self', on_delete=django.db.models.deletion.CASCADE, to='mainapp.deliverymethod', verbose_name='Способ получения'),
        ),
    ]
