# Generated by Django 3.1.3 on 2020-11-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20201123_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.CharField(default='бесплатно', max_length=9, verbose_name='Стоимость')),
                ('form_label', models.CharField(max_length=256, verbose_name='Текст отображения в форме')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.receivemethod', verbose_name='Способ получения'),
        ),
        migrations.DeleteModel(
            name='DeliveryMethod',
        ),
    ]
