# Generated by Django 3.1.3 on 2020-11-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20201124_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivemethod',
            name='is_free',
        ),
    ]
