# Generated by Django 3.1.3 on 2020-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_remove_receivemethod_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Общая стоимость'),
        ),
    ]
