# Generated by Django 3.1.3 on 2020-11-24 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20201124_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivemethod',
            name='form_label',
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_method',
            field=models.ForeignKey(default='Самовывоз', on_delete=django.db.models.deletion.CASCADE, to='mainapp.receivemethod', verbose_name='Способ получения'),
        ),
    ]
