# Generated by Django 3.1.3 on 2020-11-24 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0030_auto_20201124_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес')),
                ('apartment_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('porch_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Подъезд')),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('intercom', models.CharField(blank=True, max_length=256, null=True, verbose_name='Код домофона')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='customer',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.address', verbose_name='Адреса'),
        ),
    ]
