# Generated by Django 3.1.3 on 2020-11-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20201124_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Название'),
        ),
    ]
