# Generated by Django 3.1.3 on 2020-12-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ('product',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.CreateModel(
            name='ProductPhoto1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('product',),
            },
        ),
    ]
