# Generated by Django 3.1.3 on 2020-12-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_productphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPhoto1',
            new_name='ProductPhoto',
        ),
    ]
