# Generated by Django 3.1.3 on 2020-12-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activation_code',
            field=models.PositiveIntegerField(max_length=5, null=True),
        ),
    ]
