# Generated by Django 3.1.3 on 2020-12-11 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Населённый пункт')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('apartment_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('porch_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Подъезд')),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('intercom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код домофона')),
                ('full_passport_name', models.CharField(max_length=255, verbose_name='Фамилия и Имя по паспорту')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=63, verbose_name='Электронная почта')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(default=datetime.time(12, 0), verbose_name='Время доставки')),
                ('payment_method', models.CharField(choices=[('card_online', 'Картой онлайн'), ('cash', 'Наличными при получении')], default='card_online', max_length=255, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ находится в обработке'), ('is_ready', 'Заказ готов'), ('in_delivery', 'Передан в службу доставки'), ('delivered', 'Заказ доставлен'), ('completed', 'Заказ выполнен')], default='new', max_length=63, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReceiveMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='receive_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.receivemethod', verbose_name='Способ получения'),
        ),
    ]
